# Generated by Django 2.2.7 on 2020-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('Problem_Id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Problem_Title', models.CharField(max_length=200)),
                ('Problem_Description', models.TextField()),
                ('Problem_Input', models.TextField()),
                ('Problem_Output', models.TextField()),
                ('Problem_Simple_Input', models.TextField()),
                ('Problem_Simple_Output', models.TextField()),
                ('Problem_Spj', models.IntegerField(default=0)),
                ('Problem_Hint', models.TextField()),
                ('Problem_Source', models.CharField(max_length=100)),
                ('Problem_Sample_Program', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
