# Generated by Django 2.2.7 on 2020-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200326_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='Problem_Id',
            field=models.IntegerField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
